baseurl = 'https://yannisza.github.io/'
languageCode = 'en-uk'
title = 'Ioannis (Yannis) Zachos'
# Default Theme
theme = 'gruvhugo'
# Number of posts per page
paginate = "10" 
#disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-G1VHH9QBW3" # Enable Google Analytics by entering your tracking id
#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------



# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "yannis, ioannis, zachos, machine, learning, PhD, computational, statistics, agent-based, modelling, multi-agent systems"
  headerTitle = "Ioannis (Yannis) Zachos"
  copyright = ""
  name = "yannis_zachos"
  img = "img/IoannisZachos.png"
  img_title = ""
  icon = "img/icon_hu41d8108e0a3a94dc63cb93224846b6ff_203010_512x512_fill_lanczos_center_2.png"
  quote = "Doctoral Researcher in Computational Statistics"
  description= "I am a final year PhD student in the interdisciplinary <a href=\"https://www.fibe-cdt.eng.cam.ac.uk/\", target=\"_blank\"> CDT in Future Infrastructure and Built Environment</a> at the University of Cambridge supervised by <a href=\"https://en.wikipedia.org/wiki/Mark_Girolami\", target=\"_blank\">Professor Mark Girolami</a> and co-funded by <a href=\"https://www.arup.com/\", target=\"_blank\">Arup</a> and <a href=\"https://www.ukri.org/councils/epsrc/\", target=\"_blank\">EPSRC</a>. My research focuses on eliciting individual agent dynamics from aggregate data using Markov Bases, Markov Chain Monte Carlo, and Physics-informed ML. I am passionate about developing Computational Statistics and Machine Learning models for industry-relevant Research and Development. My full CV can be found <a href=\"../../files/CV.pdf\", target=\"_blank\">here</a>."
  licenseUrl = ""

 # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/YannisZa"

  [[params.social]]
    name = "email"
    url  = "mailto:yzachos@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/izachos/"

[params.style]
  # add path to custom CSS files here
  custom_css = ['css/style.css']
  # add path to custom SCSS files here
  custom_scss = []

[menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name       = "About"
  #   url        = "about"

  [[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "news/"
    
  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "files/CV.pdf"

  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "research/"

  [[menu.main]]
    identifier = "reading"
    name       = "Reading"
    url        = "reading/"


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

